Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "tasnims-tp2" do |server|
    server.vm.hostname = "tasnims-tp2"
    server.vm.network "private_network", ip: "192.168.56.120"
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = "tasnims-tp2"
      vb.memory = 1024
      vb.cpus = 1
    end

    # Provision automatique K3s
    server.vm.provision "shell", inline: <<-SHELL
      echo "=== Installation de K3s sur tasnims-tp2 ==="
      if ! command -v k3s &> /dev/null; then
        curl -sfL https://get.k3s.io | sh -
      else
        echo "K3s déjà installé sur tasnims-tp2"
      fi
    SHELL
  end
end
