---
- name: Déploiement des applications sur le cluster K3s
  hosts: all
  become: yes
  tasks:
    - name: Copier les fichiers YAML dans la VM
      copy:
        src: ./files/
        dest: /home/vagrant/apps/
        owner: vagrant
        mode: '0644'

    - name: Appliquer les fichiers YAML sur le cluster
      shell: |
        kubectl apply -f /home/vagrant/apps/apps.yaml
        kubectl apply -f /home/vagrant/apps/ingress.yaml
      args:
        executable: /bin/bash
