Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "ansible-k3s"
  config.vm.network "private_network", ip: "192.168.56.30"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ansible-k3s"
    vb.memory = 1024
    vb.cpus = 1
  end

  # Installe Ansible et exécute le playbook à l’intérieur de la VM
  config.vm.provision "shell", inline: <<-SHELL
    apt update -y
    apt install -y ansible
    mkdir -p /home/vagrant/ansible
    cp /vagrant/playbook.yml /home/vagrant/ansible/
    cp /vagrant/inventory.ini /home/vagrant/ansible/
    cd /home/vagrant/ansible
    ansible-playbook -i inventory.ini playbook.yml
  SHELL
end
